### ISSUE TITLE
Extension is not working with spotify on windows 11

### ISSUE THREAD

**Issue by Big-mac23** [trimone9000/vscode-media-manager#2]
Hi, I recently downloaded the extension and it does not show the music that is playing in spotify.
![image](https://github.com/alessandro-murtas/vscode-media-manager/assets/146560171/5dd3d0ae-e2ea-4207-82c3-d15c3cbada4f)
I have attached an image of me playing music and the extension not picking it up. I have tried restarting the extensions and restarted vs code multiple times, but the issue persists.

**Comment by alessandro-murtas** [comment]
Hi sorry if i reply only now. Do you have Python installed on your computer? I forgot to include this in the README but it is required for the extension to work. If you could try it again and let me know if it works it would be helpful.

Thanks

**Comment by Big-mac23** [comment]
Yep I have python installed. I even recently reinstalled vscode and python again because of a windows reinstall and this extension does not work.

**Comment by alessandro-murtas** [comment]
Ok I think I might've found what you need to do to make it work, you just need to install with pip the following packages:

- pywin32
- winsdk
- vscode-ext

If you could try to install them and tell me if the extension works I'll add them to the README and mark this issue as solved.
Thanks

**Comment by Big-mac23** [comment]
I was missing the winsdk file and after installing it, the extension works perfectly now. Thanks for the help.

**Comment by alessandro-murtas** [comment]
Thanks to you, this way I can fix the README for everybody else.
